---
abstract: 'Parse Perl string literals and string-literal-like things.'
author:
  - 'Thomas R. Wyant, III F<wyant at cpan dot org>'
build_requires:
  Test::More: '0.88'
  charnames: '0'
configure_requires:
  lib: '0'
  strict: '0'
  warnings: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PPIx-QuoteLike
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
provides:
  PPIx::QuoteLike:
    file: lib/PPIx/QuoteLike.pm
    version: '0.018'
  PPIx::QuoteLike::Constant:
    file: lib/PPIx/QuoteLike/Constant.pm
    version: '0.018'
  PPIx::QuoteLike::Dumper:
    file: lib/PPIx/QuoteLike/Dumper.pm
    version: '0.018'
  PPIx::QuoteLike::Token:
    file: lib/PPIx/QuoteLike/Token.pm
    version: '0.018'
  PPIx::QuoteLike::Token::Control:
    file: lib/PPIx/QuoteLike/Token/Control.pm
    version: '0.018'
  PPIx::QuoteLike::Token::Delimiter:
    file: lib/PPIx/QuoteLike/Token/Delimiter.pm
    version: '0.018'
  PPIx::QuoteLike::Token::Interpolation:
    file: lib/PPIx/QuoteLike/Token/Interpolation.pm
    version: '0.018'
  PPIx::QuoteLike::Token::String:
    file: lib/PPIx/QuoteLike/Token/String.pm
    version: '0.018'
  PPIx::QuoteLike::Token::Structure:
    file: lib/PPIx/QuoteLike/Token/Structure.pm
    version: '0.018'
  PPIx::QuoteLike::Token::Unknown:
    file: lib/PPIx/QuoteLike/Token/Unknown.pm
    version: '0.018'
  PPIx::QuoteLike::Token::Whitespace:
    file: lib/PPIx/QuoteLike/Token/Whitespace.pm
    version: '0.018'
  PPIx::QuoteLike::Utils:
    file: lib/PPIx/QuoteLike/Utils.pm
    version: '0.018'
requires:
  Carp: '0'
  Encode: '0'
  Exporter: '0'
  List::Util: '0'
  PPI::Document: '1.117'
  PPI::Dumper: '1.117'
  Readonly: '0'
  Scalar::Util: '0'
  Text::Tabs: '0'
  base: '0'
  constant: '0'
  perl: '5.006'
  re: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=PPIx-QuoteLike
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trwyant/perl-PPIx-QuoteLike.git
version: '0.018'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
